{
 "title": "Example Prometheus Dashboard",
 "description": "Example Grafana dashboard for Prometheus metrics.",
 "tags": [
  "example",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Healthy Targets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(up == 1)" }
   ]
  },
  {
   "title": "Average Prometheus Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "avg(scrape_duration_seconds)" }
   ]
  },
  {
   "title": "Prometheus TSDB Head Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series" }
   ]
  }
 ]
}