version: '3.8'

services:
  web:
    build: ../app
    container_name: homelab-nginx
    ports:
      - "127.0.0.1:${NGINX_PORT}:80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    image: hashicorp/http-echo
    container_name: homelab-api
    command: [ "-text=hello from api" ]
    restart: unless-stopped
