name: Homelab CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/homelab-web

          docker build \
            -t $IMAGE:latest \
            -t $IMAGE:${{ github.sha }} \
            ./app

          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}

      - name: List images
        run: docker images